### ISSUE TITLE
Logo/Icon Proposal

### ISSUE THREAD

**Issue by jbeguna04** [journaldev/journaldev#3]
Greetings, Im a graphics designer here on Github and I would like to ask for your permission to design for your logo/icon that you maybe used for your future plans in your project. I want to help open source projects by designing logos or banners for there project. Thank you for your time reading this

Best regards
-jbeguna04

**Comment by journaldev** [comment]
Sure, go ahead.

**Comment by jbeguna04** [comment]
Thank you for your response. Ill be sending the designs asap

**Comment by jbeguna04** [comment]
Greetings @journaldev , I would like to ask more information about the project so that I can have more ideas what would be the icon/logo output?
Thank you in advance!

**Comment by journaldev** [comment]
We provide high-quality tutorials on various technical topics in Java, Spring, Python, Android etc. Our GitHub repository contains all these projects and makes it readily available to everyone.

**Comment by jbeguna04** [comment]
![jd](https://user-images.githubusercontent.com/35353768/42667784-ff06e1f0-867f-11e8-983d-ccf57a7f9472.png)

Greetings @journaldev , Here some proposal for the logo. The logo consist of letter "J" and "D" for initials and Having the concept of Dev in the Logo. Hoping for your response about the logo. Thank you!

**Comment by jbeguna04** [comment]
@journaldev , Greetings! What do you think about the logo designs?

**Comment by jbeguna04** [comment]
@journaldev , Greetings sir, What do you think about the logo designs? Feel free to open suggestions about it. Thank you!

**Comment by jbeguna04** [comment]
Sure, I can provide it now. Do you want me to commit the files with doing a PR?

**Comment by jbeguna04** [comment]
@journaldev , Hello sir. Any update on the logo I made?

**Comment by journaldev** [comment]
The PR has been merged, thanks for your help in designing the logo.

**Comment by jbeguna04** [comment]
Thank you. Hope it can help :)
