### ISSUE TITLE
Changing the categories from  String[] to an edittext

### ISSUE THREAD

**Issue by daniel702707** [journaldev/journaldev#5]
Hello I'm new to programming and not sure how to change the spinner from the AndroidRoomTodo project. How to change the categories String[] to an edittext. could you help me out? Thank you

**Comment by journaldev** [comment]
If you need any help regarding the project, please use the comments section on the article page. 

[Android Room Todo List Article](https://www.journaldev.com/20688/android-room-todo-list-application)
