### ISSUE TITLE
How to get the callback when we drop the row?

### ISSUE THREAD

**Issue by kidsh3148** [journaldev/journaldev#6]
@journaldev I need the callback when I will drop the raw on a specific position, yes we are getting the callback for row moved using `public void onRowMoved(int fromPosition, int toPosition)`.
But I need to call the API when I have completed my dragging from one position to another to notify the server, if I will call the API every time when moving then this will creates too many counts for the API calls.

Please let me know if there is a possible solution for this.

**Comment by journaldev** [comment]
Can you provide more details? Post URL, GitHub code you are referring etc.?
